---
networks:
  default:
    external: true
    name: proxynet

services:
  readarr-audio:
    container_name: readarr-audio
    hostname: readarr-audio
    image: ghcr.io/hotio/readarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      PUID: 950
      PGID: 950
      UMASK: 002
      TZ: America/Los_Angeles
    volumes:
      - /mnt/store/containers/readarr-audio:/config
      - /mnt/store/media:/data
