---
- Networking:
    - Netgear Managed Switch:
        href: http://hawkeye.lan
        icon: si-netgear
        description: hawkeye
        siteMonitor: http://hawkeye.lan

    - Linksys Router:
        href: http://thor.lan
        icon: si-linksys
        description: thor
        siteMonitor: http://thor.lan

    - Linksys Access Point 1:
        href: http://ironman.lan
        icon: si-linksys
        description: ironman
        siteMonitor: http://ironman.lan

    - Linksys Access Point 2:
        href: http://blackwidow.lan
        icon: si-linksys
        description: black widow
        siteMonitor: http://blackwidow.lan

    - Nginx Proxy Manager:
        href: http://npm.lan
        icon: si-nginxproxymanager
        description: nginx proxy manager
        server: kevins_dockerproxy
        container: nginx-proxy-manager
        widget:
          type: npm
          url: http://npm.lan
          username: {{HOMEPAGE_VAR_NPM_USERNAME}}
          password: {{HOMEPAGE_VAR_NPM_PASSWORD}}

- Infrastructure and Data:
    - TrueNAS Scale:
        href: http://kevin.lan
        icon: si-truenas
        description: kevin
        siteMonitor: http://kevin.lan
        widget:
          type: truenas
          url: http://kevin.lan
          key: {{HOMEPAGE_VAR_TRUENAS_KEY}}
          enablePools: true
          nasType: scale

    - Synology:
        href: http://syno.lan
        icon: si-synology
        description: Synology D218+
        siteMonitor: http://syno.lan
        widget:
          type: diskstation
          url: http://syno.lan
          username: {{HOMEPAGE_VAR_SYNO_USERNAME}}
          password: {{HOMEPAGE_VAR_SYNO_PASSWORD}}
          volume: volume_1

    - GitHub Runner:
        href: http://github.com/wesleyem/homelab/
        icon: si-github
        description: octorunner
        server: kevins_dockerproxy
        container: github-runner

    - Docker Proxy:
        href: http://portainer.lan
        icon: si-docker
        description: docker proxy
        server: kevins_dockerproxy
        container: dockerproxy

    - AdGuard Home:
        href: http://adguard.lan
        icon: si-adguard
        description: DNS Server
        server: kevins_dockerproxy
        container: adguard
        widget:
          type: adguard
          url: http://adguard.lan
          username: {{HOMEPAGE_VAR_ADGUARD_USERNAME}}
          password: {{HOMEPAGE_VAR_ADGUARD_PASSWORD}}

    - WireGuard:
        href: http://wg.lan
        icon: si-wireguard
        description: wireguard vpn
        server: kevins_dockerproxy
        container: wg-easy
        widget:
          type: wgeasy
          url: http://wg.lan
          password: {{HOMEPAGE_VAR_WGEASY_PASSWORD}}

- Management:
    - Portainer:
        href: http://portainer.lan
        icon: si-portainer
        description: portainer
        server: kevins_dockerproxy
        container: portainer
        widget:
          type: portainer
          url: http://portainer.lan
          env: 2
          key: {{HOMEPAGE_VAR_PORTAINER_KEY}}

    - Homepage:
        href: http://homepage.lan
        icon: si-homepage
        description: My Awesome Homepage
        server: kevins_dockerproxy
        container: homepage

    - Cloudflare Tunnel:
        href: https://dash.cloudflare.com
        icon: si-cloudflare
        description: Cloudflare Tunnels
        server: kevins_dockerproxy
        container: cloudflared
        widget:
          type: cloudflared
          accountid: {{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID}}
          tunnelid: {{HOMEPAGE_VAR_CLOUDFLARED_TUNNELID}}
          key: {{HOMEPAGE_VAR_CLOUDFLARED_KEY}}
