---
networks:
  default:
    external: true
    name: proxynet

services:
  portainer-ce:
    container_name: portainer
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/mnt/store/containers/portainer/data:/data"
    image: "portainer/portainer-ce:latest"
