site_name: My Homelab Documentation
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
nav:
  - Home: index.md
  - Docker:
      - Main: docker/index.md
      - AdGuard Home: docker/adguard/index.md
      - Cloudflared: docker/cloudflared/index.md
      - Homepage: docker/homepage/index.md
      - Overseerr: docker/overseerr/index.md
      - Plex: docker/plex/index.md
      - Prowlarr: docker/prowlarr/index.md
      - Radarr: docker/radarr/index.md
      - Readarr: docker/readarr/index.md
      - Readarr-audio: docker/readarr-audio/index.md
      - Sonarr: docker/sonarr/index.md
      - Tautulli: docker/tautulli/index.md
      - Nginx Proxy Manager: docker/nginx-proxy-manager/index.md
      - Octorunner: docker/octorunner/index.md
      - Portainer: docker/portainer/index.md
      - qBittorrent: docker/qbittorrent/index.md
      - WireGuard: docker/wg-easy/index.md
  - Automation:
      - Main: automation/index.md
      - Cloudflare DNS Update: automation/ddns/index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
