version: "3.7"

networks:
  default:
    name: basket
    external: true

services:
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    restart: unless-stopped
    ports:
      - "9696:9696"
    environment:
      - PUID=995
      - PGID=997
      - UMASK=002
      - TZ=America/Los_Angeles
    volumes:
      - /etc/docker/prowlarr:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      - traefik.http.routers.prowlarr-http.entrypoints=web
      - traefik.http.routers.prowlarr-http.rule=Host(`prowlarr.home.wesleyem.com`)
      - traefik.http.routers.prowlarr-https.entrypoints=websecure
      - traefik.http.routers.prowlarr-https.rule=Host(`prowlarr.home.wesleyem.com`)
      - traefik.http.routers.prowlarr-https.tls=true
      - traefik.http.routers.prowlarr-https.tls.certresolver=staging
