---
services:
  plex:
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=America/Los_Angeles
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=${ADVERTISEIP}
    hostname: ${HOST_HOSTNAME}
    volumes:
      - /volume1/docker/pms/database:/config
      - /volume1/docker/pms/transcode:/transcode
      - /volume1/data/media:/data
