---
networks:
  default:
    external: true
    name: proxynet

services:
  plex:
    devices:
      - /dev/dri:/dev/dri
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      PLEX_UID: 950
      PLEX_GID: 950
      UMASK: 002
      TZ: America/Los_Angeles
      PLEX_CLAIM: ${PLEX_CLAIM}
      ADVERTISE_IP: "http://plex.lan"
      HOSTNAME: plex
    hostname: plex
    volumes:
      - /mnt/store/containers/pms/database:/config
      - /mnt/store/containers/pms/transcode:/transcode
      - /mnt/store/media:/data
