version: "3.3"

networks:
  default:
    name: basket
    external: true

services:
  speedtest:
    container_name: speedtest
    ports:
      - ${WEB_PORT:-8080}:80
      - ${SECURE_PORT:-8443}:443
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: sqlite
      SPEEDTEST_SCHEDULE: 0 0/4 * * *
      SPEEDTEST_SERVERS: 14236,16620
      PRUNE_RESULTS_OLDER_THAN: 90
      DISPLAY_TIMEZONE: America/Los_Angeles
      APP_TIMEZONE: America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/docker/speedtest/config:/config
      - /etc/docker/speedtest/web:/etc/ssl/web
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.speedtest-http.entrypoints: web
      traefik.http.routers.speedtest-http.rule: Host(`speedtest.home.wesleyem.com`)
      traefik.http.routers.speedtest-https.entrypoints: websecure
      traefik.http.routers.speedtest-https.rule: Host(`speedtest.home.wesleyem.com`)
      traefik.http.routers.speedtest-https.tls: true
      traefik.http.routers.speedtest-https.tls.certresolver: production

