version: "3.3"

networks:
  default:
    name: basket
    external: true

services:
  speedtest:
    container_name: speedtest
    ports:
      - ${WEB_PORT:-8080}:80
      - ${SECURE_PORT:-8443}:443
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: speedtest
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_KEY: ${APP_KEY}
      APP_TIMEZONE: America/Los_Angeles
      DISPLAY_TIMEZONE: America/Los_Angeles
      SPEEDTEST_SCHEDULE: 0 0/4 * * *
      SPEEDTEST_SERVERS: 14236,16620
      PRUNE_RESULTS_OLDER_THAN: 90
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/docker/speedtest/config:/config
      - /etc/docker/speedtest/web:/etc/ssl/web
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    depends_on:
      - db
    labels:
      traefik.enable: true
      traefik.http.routers.speedtest-http.entrypoints: web
      traefik.http.routers.speedtest-http.rule: Host(`speedtest.home.wesleyem.com`)
      traefik.http.routers.speedtest-https.entrypoints: websecure
      traefik.http.routers.speedtest-https.rule: Host(`speedtest.home.wesleyem.com`)
      traefik.http.routers.speedtest-https.tls: true
      traefik.http.routers.speedtest-https.tls.certresolver: production
  db:
    image: mariadb:10
    restart: always
    environment:
      MARIADB_DATABASE: speedtest
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_RANDOM_ROOT_PASSWORD: true
      TZ: America/Los_Angeles
    volumes:
      - speedtest-db:/var/lib/mysql
    labels:
      traefik.enable: false
volumes:
  speedtest-db: {}
