---
volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=syno.lan,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nolock,soft,nfsvers=4"
      device: ":/volume1/data/"

networks:
  default:
    name: white_orchard
    external: true

services:
  qbittorrent:
    hostname: qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    image: ghcr.io/hotio/qbittorrent:release-4.6.7
    ports:
      - 8881:8080
      - 8118:8118
    environment:
      TZ: Etc/UTC
      VPN_ENABLED: true
      VPN_PROVIDER: proton
      VPN_LAN_NETWORK: 10.100.0.0/24
      VPN_CONF: wg0
      PRIVOXY_ENABLED: false
    volumes:
      - /home/ubuntu/qbittorrent:/config
      - data:/data
    cap_add:
      - NET_ADMIN
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv6.conf.all.disable_ipv6: 1
