version: "3"

networks:
  default:
    name: basket
    external: true

services:
  overseerr:
    container_name: overseerr
    image: sctx/overseerr:latest
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - TZ=America/Los_Angeles
    ports:
      - 5055:5055
    volumes:
      - /etc/docker/overseerr:/app/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.lan`, `os.wesleyem.com`)"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
