---
networks:
  default:
    external: true
    name: proxynet

services:
  overseerr:
    container_name: overseerr
    image: sctx/overseerr:latest
    restart: unless-stopped
    environment:
      LOG_LEVEL: info
      TZ: America/Los_Angeles
    ports:
      - 5055:5055
    volumes:
      - /mnt/store/containers/overseerr:/app/config
