version: "3.7"

volumes:
  rclone_data:
    driver: rclone
    driver_opts:
      remote: "rclone-remote"
      path: "docker/prowlarr"
      allow_other: "true"
      vfs_cache_mode: full
      poll_interval: 0

networks:
  sprinkles:
    external: true

services:
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - rclone_data:/config
    networks:
      - sprinkles
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.home`)"
        - "providers.docker.network=sprinkles"
