---
networks:
  default:
    external: true
    name: my-macvlan-net
services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    volumes:
      - /mnt/store/containers/adguard/work:/opt/adguardhome/work
      - /mnt/store/containers/adguard/conf:/opt/adguardhome/conf
