---
networks:
  default:
    external: true
    name: proxynet

services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    volumes:
      - /mnt/store/containers/adguard/work:/opt/adguardhome/work
      - /mnt/store/containers/adguard/conf:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 83:80/tcp
      - 9444:443/tcp
      - 9444:443/udp
      - 3000:3000/tcp
      - 853:853/tcp
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
