# adguard
version: "3.3"
# define custom network
networks:
  traefik:
    external: true

services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    networks: [traefik]
    volumes:
      - ${ADGUARD_WORK}:/opt/adguardhome/work
      - ${ADGUARD_CONF}:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 81:80/tcp
      - 444:443/tcp
      - 444:443/udp
      - 3000:3000/tcp
      - 853:853/tcp
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`${HOST_NAME}`)"
      - "traefik.http.services.adguard.loadbalancer.server.port=80"
