---
services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    network_mode: macvlan
    restart: unless-stopped
    volumes:
      - /mnt/store/containers/adguard/work:/opt/adguardhome/work
      - /mnt/store/containers/adguard/conf:/opt/adguardhome/conf
