version: "3"
# define custom network
networks:
  default:
    name: basket
    external: true

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: ${TZ}
      WATCHTOWER_CLEANUP: "true"
      # WATCHTOWER_SCHEDULE: "0 0 3 * * *"
      WATCHTOWER_POLL_INTERVAL: 30
      WATCHTOWER_ROLLING_RESTART: "true"
      WATCHTOWER_NOTIFICATION_URL: ${WATCHTOWER_NOTIFICATION_URL}
      WATCHTOWER_HTTP_API_TOKEN: ${WATCHTOWER_HTTP_API_TOKEN}
      WATCHTOWER_HTTP_API_METRICS: "true"
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      WATCHTOWER_NOTIFICATION_TEMPLATE: |
        {{- if .Report -}}
          {{- with .Report -}}
            {{- if ( or .Updated .Failed ) -}}
        {{len .Scanned}} Scanned, {{len .Updated}} Updated, {{len .Failed}} Failed
              {{- range .Updated}}
        - {{.Name}} ({{.ImageName}}): {{.CurrentImageID.ShortID}} updated to {{.LatestImageID.ShortID}}
              {{- end -}}
              {{- range .Fresh}}
        - {{.Name}} ({{.ImageName}}): {{.State}}
              {{- end -}}
              {{- range .Skipped}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
              {{- end -}}
              {{- range .Failed}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
              {{- end -}}
            {{- end -}}
          {{- end -}}
        {{- else -}}
          {{range .Entries -}}{{.Message}}{{"\n"}}{{- end -}}
        {{- end -}}
    ports:
      - 8082:8080
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.services.watchtower.loadbalancer.server.port: 8080
      traefik.http.routers.watchtower-http.entrypoints: web
      traefik.http.routers.watchtower-http.rule: Host(`${HOST_HOSTNAME}.watchtower.home.wesleyem.com`)
      traefik.http.routers.watchtower-https.entrypoints: websecure
      traefik.http.routers.watchtower-https.rule: Host(`${HOST_HOSTNAME}.watchtower.home.wesleyem.com`)
      traefik.http.routers.watchtower-https.tls: true
      traefik.http.routers.watchtower-https.tls.certresolver: production