version: '3'

networks:
  default:
    name: basket
    external: true

services:
  vikunja:
    image: vikunja/vikunja
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://vikunja.home.wesleyem.com
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: ${VIKUNJA_SERVICE_JWTSECRET}
      VIKUNJA_SERVICE_ENABLEREGISTRATION: false
    ports:
      - 3456:3456
    volumes: 
      - /etc/docker/vikunja/files:/app/vikunja/files
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.vikunja-http.entrypoints: web
      traefik.http.routers.vikunja-http.rule: Host(`vikunja.home.wesleyem.com`)
      traefik.http.routers.vikunja-https.entrypoints: websecure
      traefik.http.routers.vikunja-https.rule: Host(`vikunja.home.wesleyem.com`)
      traefik.http.routers.vikunja-https.tls: true
      traefik.http.routers.vikunja-https.tls.certresolver: production
  db:
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_USER: vikunja
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: vikunja
    volumes:
      - /etc/docker/vikunja/db:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"]
      interval: 2s
      start_period: 30s
