---
services:
  app:
    container_name: nginx-proxy-manager
    image: "jc21/nginx-proxy-manager:latest"
    network_mode: host
    restart: unless-stopped
    volumes:
      - /mnt/store/containers/npm/data:/data
      - /mnt/store/containers/npm/letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
