---
networks:
  default:
    external: true
    name: proxynet

services:
  sabnzbd:
    container_name: sabnzbd
    hostname: sabnzbd
    restart: unless-stopped
    image: ghcr.io/hotio/sabnzbd:latest
    ports:
      - 8081:8080
    environment:
      - PUID=950
      - PGID=950
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8080/tcp,8080/udp
      - ARGS
      - VPN_ENABLED=true
      - VPN_PROVIDER=proton
      - VPN_CONF=wg0
      - VPN_LAN_NETWORK=10.100.0.0/16
    volumes:
      - /mnt/store/containers/sabnzbd:/config
      - /mnt/store/media:/data
    cap_add:
      - NET_ADMIN
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv6.conf.all.disable_ipv6: 1
