---
networks:
  default:
    name: basket
    external: true

services:
  qbittorrent:
    container_name: qbittorrent
    restart: unless-stopped
    image: ghcr.io/hotio/qbittorrent:latest
    ports:
      - 8881:8080
      - 8118:8118
    environment:
      UMASK: 002
      TZ: Etc/UTC
      VPN_ENABLED: true
      VPN_PROVIDER: proton
      VPN_LAN_NETWORK: 10.100.0.0/24
      VPN_CONF: wg0
      PRIVOXY_ENABLED: false
    volumes:
      - /mnt/syno_docker_nfs/qbittorrent:/config
      - /mnt/syno_data_nfs:/data
    cap_add:
      - NET_ADMIN
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv6.conf.all.disable_ipv6: 1
    labels:
      traefik.enable: true
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8080
      traefik.http.routers.qbittorrent-http.entrypoints: web
      traefik.http.routers.qbittorrent-http.rule: Host(`qbittorrent.${HOST_HOSTNAME}.home.wesleyem.com`)
      traefik.http.routers.qbittorrent-https.entrypoints: websecure
      traefik.http.routers.qbittorrent-https.rule: Host(`qbittorrent.${HOST_HOSTNAME}.home.wesleyem.com`)
      traefik.http.routers.qbittorrent-https.tls: true
      traefik.http.routers.qbittorrent-https.tls.certresolver: production
