---
networks:
  basket:
    external: true

volumes:
  wireguard: {}

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    networks:
      - basket
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=${WG_HOST} #optional
      - SERVERPORT=${WG_PORT} #optional
      - PEERS=AniPhone #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=10.0.0.0/8 #optional
      - PERSISTENTKEEPALIVE_PEERS=${PEER1} #optional
      - LOG_CONFS=true #optional
    volumes:
      - wireguard:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - ${WG_PORT}:${WG_PORT}/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
