---
networks:
  default:
    external: true
    name: proxynet

services:
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      PUID: 950
      PGID: 950
      UMASK: 002
      TZ: America/Los_Angeles
    volumes:
      - /mnt/store/containers/prowlarr:/config

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      PUID: 950
      PGID: 950
      UMASK: 002
      TZ: America/Los_Angeles
    volumes:
      - /mnt/store/containers/radarr:/config
      - /mnt/store/media:/data

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      PUID: 950
      PGID: 950
      UMASK: 002
      TZ: America/Los_Angeles
    volumes:
      - /mnt/store/containers/sonarr:/config
      - /mnt/store/media:/data

  readarr:
    container_name: readarr
    image: ghcr.io/hotio/readarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8787:8787
    environment:
      PUID: 950
      PGID: 950
      UMASK: 002
      TZ: America/Los_Angeles
    volumes:
      - /mnt/store/containers/readarr:/config
      - /mnt/store/media:/data

  readarr-audio:
    container_name: readarr-audio
    image: ghcr.io/hotio/readarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8788:8787
    environment:
      PUID: 950
      PGID: 950
      UMASK: 002
      TZ: America/Los_Angeles
    volumes:
      - /mnt/store/containers/readarr-audio:/config
      - /mnt/store/media:/data

  plex:
    devices:
      - /dev/dri:/dev/dri
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      PLEX_UID: 950
      PLEX_GID: 950
      UMASK: 002
      TZ: America/Los_Angeles
      PLEX_CLAIM: ${PLEX_CLAIM}
      ADVERTISE_IP: "http://plex.lan"
      HOSTNAME: plex
    hostname: plex
    volumes:
      - /mnt/store/containers/pms/database:/config
      - /mnt/store/containers/pms/transcode:/transcode
      - /mnt/store/media:/data

  tautulli:
    container_name: tautulli
    image: ghcr.io/hotio/tautulli:latest
    environment:
      PUID: 950
      PGID: 950
      UMASK: 002
      TZ: America/Los_Angeles
    ports:
      - 8181:8181
    volumes:
      - /mnt/store/containers/tautulli:/config
    restart: unless-stopped

  overseerr:
    container_name: overseerr
    image: sctx/overseerr:latest
    restart: unless-stopped
    environment:
      LOG_LEVEL: info
      TZ: America/Los_Angeles
    ports:
      - 5055:5055
    volumes:
      - /mnt/store/containers/overseerr:/app/config
