version: "3.2"

volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=syno,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nolock,soft,nfsvers=4"
      device: ":/volume1/data/"
  readarr: {}

networks:
  default:
    name: basket
    external: true

services:
  readarr:
    container_name: readarr
    image: ghcr.io/hotio/readarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8787:8787
    environment:
      TZ: America/Los_Angeles
    volumes:
      - readarr:/config
      - data:/data
    labels:
      traefik.enable: true
      traefik.http.routers.readarr-http.entrypoints: web
      traefik.http.routers.readarr-http.rule: Host(`readarr.home.wesleyem.com`)
      traefik.http.routers.readarr-https.entrypoints: websecure
      traefik.http.routers.readarr-https.rule: Host(`readarr.home.wesleyem.com`)
      traefik.http.routers.readarr-https.tls: true
      traefik.http.routers.readarr-https.tls.certresolver: production
