---
networks:
  default:
    external: true
    name: proxynet

services:
  readarr:
    container_name: readarr
    hostname: readarr
    image: ghcr.io/hotio/readarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8787:8787
    environment:
      PUID: 950
      PGID: 950
      UMASK: 002
      TZ: America/Los_Angeles
    volumes:
      - /mnt/store/containers/readarr:/config
      - /mnt/store/media:/data
