---
networks:
  default:
    name: basket
    external: true

services:
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      UMASK: 002
      TZ: America/Los_Angeles
    volumes:
      - /mnt/syno_docker_nfs/sonarr:/config
      - /mnt/syno_data_nfs:/data
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr-http.entrypoints: web
      traefik.http.routers.sonarr-http.rule: Host(`sonarr.home.wesleyem.com`)
      traefik.http.routers.sonarr-https.entrypoints: websecure
      traefik.http.routers.sonarr-https.rule: Host(`sonarr.home.wesleyem.com`)
      traefik.http.routers.sonarr-https.tls: true
      traefik.http.routers.sonarr-https.tls.certresolver: production
