---
volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=syno.lan,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nolock,soft,nfsvers=4"
      device: ":/volume1/data/"

networks:
  default:
    name: white_orchard
    external: true

services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      TZ: America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $HOME/radarr:/config
      - data:/data
