---
networks:
  default:
    external: true
    name: proxynet

services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    ports:
      - 3001:3000
    hostname: homepage
    environment:
      PUID: 0
      PGID: 0
    volumes:
      - /mnt/store/containers/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      homepage.group: Management
      homepage.name: homepage
      homepage.icon: homepage
      homepage.href: http://homepage.lan
      homepage.description: Homepage
