version: "3.3"

networks:
  default:
    name: basket
    external: true

services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    ports:
      - 3000:3000
    volumes:
      - /etc/docker/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - traefik.http.routers.homepage-http.entrypoints=web
      - traefik.http.routers.homepage-http.rule=Host(`homepage.home.wesleyem.com`)
      - traefik.http.routers.homepage-https.entrypoints=websecure
      - traefik.http.routers.homepage-https.rule=Host(`homepage.home.wesleyem.com`)
      - traefik.http.routers.homepage-https.tls=true
      - traefik.http.routers.homepage-https.tls.certresolver=staging
