---
services:
  github-runner:
    image: ghcr.io/wesleyem/octorunner:latest
    container_name: github-runner
    environment:
      REPO_URL: https://github.com/wesleyem/homelab
      TOKEN: ${RUNNER_TOKEN}
