---
services:
  github-runner:
    container_name: github-runner
    image: ghcr.io/wesleyem/octorunner:latest
    environment:
      REPO: wesleyem/homelab
      TOKEN: ${RUNNER_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: 1001:101
