---
services:
  github-runner-1:
    image: ghcr.io/wesleyem/octorunner:latest
    environment:
      REPO: wesleyem/homelab
      TOKEN: ${RUNNER_TOKEN}

  github-runner-2:
    image: ghcr.io/wesleyem/octorunner:latest
    environment:
      REPO: wesleyem/homelab
      TOKEN: ${RUNNER_TOKEN}

  github-runner-3:
    image: ghcr.io/wesleyem/octorunner:latest
    environment:
      REPO: wesleyem/homelab
      TOKEN: ${RUNNER_TOKEN}
