- name: Update Portainer CE container
  hosts: "portainer_ce"
  tasks:
    - name: Pull the latest Portainer CE image
      community.docker.docker_image:
        name: portainer/portainer-ce
        source: pull
        tag: latest
        
    - name: Compose up with new image
      command: docker compose --project-directory /etc/docker/portainer/ up -d