version: '3.7'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data
    labels:
      uptimekuma.enable: true
      uptimekuma.http.routers.uptimekuma-http.entrypoints: web
      uptimekuma.http.routers.uptimekuma-http.rule: Host(`uptimekuma.home.wesleyem.com`)
      uptimekuma.http.routers.uptimekuma-https.entrypoints: websecure
      uptimekuma.http.routers.uptimekuma-https.rule: Host(`uptimekuma.home.wesleyem.com`)
      uptimekuma.http.routers.uptimekuma-https.tls: true
      uptimekuma.http.routers.uptimekuma-https.tls.certresolver: production

volumes:
  uptime-kuma-data:

