version: "3.7"

networks:
  default:
    name: basket
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: always
    ports:
      - "3002:3001"
    volumes:
      - uptime-kuma-data:/app/data
    labels:
      traefik.enable: true
      traefik.http.routers.uptimekuma-http.entrypoints: web
      traefik.http.routers.uptimekuma-http.rule: Host(`uptimekuma.home.wesleyem.com`)
      traefik.http.routers.uptimekuma-https.entrypoints: websecure
      traefik.http.routers.uptimekuma-https.rule: Host(`uptimekuma.home.wesleyem.com`)
      traefik.http.routers.uptimekuma-https.tls: true
      traefik.http.routers.uptimekuma-https.tls.certresolver: production

volumes:
  uptime-kuma-data: {}
