---
name: traefik

networks:
  default:
    name: white_orchard
    external: true

services:
  traefik:
    restart: unless-stopped
    image: traefik:v3
    container_name: traefik
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
