---
services:
  traefik:
    restart: unless-stopped
    image: traefik:v3
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/ubuntu/traefik:/etc/traefik
