# defines a custom network
version: "3"

networks:
  default:
    name: basket
    external: true

services:
  traefik:
    container_name: traefik
    restart: unless-stopped
    image: traefik:v2.10.5
    ports:
      - ${WEB_PORT:-80}:80
      - ${WEBSECURE_PORT:-443}:443
      # -- (Optional) Enable Dashboard, don't do in production
      - ${DASHBOARD_PORT:-8080}:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/docker/traefik:/etc/traefik
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${HOST_HOSTNAME}.traefik.lan`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
