# defines a custom network
version: "3"

networks:
  basket:
    external: true

services:
  traefik:
    container_name: traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${HOST_HOSTNAME}.traefik.lan`, `${HOST_HOSTNAME_ALT}.traefik.lan`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    image: traefik:v2.10.5
    ports:
      - 80:80
      - 443:443
      # -- (Optional) Enable Dashboard, don't do in production
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/docker/traefik:/etc/traefik
    networks:
      - basket
