# traefik
---
# defines a custom network
networks:
  traefik:
    external: true

services:
  traefik:
    image: traefik
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # -- (Optional) Enable Dashboard, don't do in production
      - 8080:8080
    volumes:
      - ${WORKING_DIR}:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: [traefik]
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${HOST_NAME}`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
