global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true
  debug: false

entryPoints:
  web:
    address: :80
  websecure:
    address: :443
  dns:
    address: ":53/udp"

#-- Configure your CertificateResolver here...
certificatesResolvers:
  staging:
    acme:
      email: wesleyem@pm.me
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      # -- (Optional) Configure DNS Challenge
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
  production:
    acme:
      email: wesleyem@pm.me
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      # -- (Optional) Configure DNS Challenge
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

# -- (Optional) Disable TLS Cert verification check
serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    exposedByDefault: true
    endpoint: "unix:///var/run/docker.sock"
    network: basket
    defaultRule: "Host(`{{ .Name }}.lan`)"
    watch: true
  file:
    directory: /etc/traefik/config/
    watch: true
