global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true
  debug: false

entryPoints:
  web:
    address: :80
  websecure:
    address: :443
  dns:
    address: ":53/udp"

providers:
  docker:
    exposedByDefault: true
    endpoint: "unix:///var/run/docker.sock"
    network: basket
    defaultRule: "Host(`{{ .Name }}.lan`)"
    watch: true
  file:
    directory: /etc/traefik/config/
    watch: true
