name: "[homepage] Update Config Files"

on:
  push:
    branches:
      - main
    paths:
      - "docker/homepage/config/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create SSH Key File
        run: |
          echo "${{ secrets.SSH_TNA_KEY }}" > ~/.ssh/homepage_key
          chmod 600 ~/.ssh/homepage_key

      - name: Copy Config Files via SCP
        run: |
          scp -i ~/.ssh/homepage_key \
              -o StrictHostKeyChecking=no \
              -r ./docker/homepage/config/* \
              ${{ secrets.SSH_TNA_USERNAME }}@${{ secrets.HOST }}:/mnt/store/containers/homepage/

      - name: Restart Docker Container via SSH
        run: |
          ssh -i ~/.ssh/homepage_key \
              -o StrictHostKeyChecking=no \
              ${{ secrets.SSH_TNA_USERNAME }}@${{ secrets.HOST }} \
              "docker container restart homepage"

      - name: Remove SSH Key File
        if: always()
        run: |
          rm -f ~/.ssh/homepage_key
