name: "[homepage] Update Config Files"

on:
  push:
    branches:
      - main
    paths:
      - "docker/homepage/config/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Use native SCP to transfer files
      - name: Copy Config Files via SCP
        run: |
          scp -i "${{ secrets.SSH_TNA_KEY }}" \
              -o StrictHostKeyChecking=no \
              -r ./docker/homepage/config/* \
              ${{ secrets.SSH_TNA_USERNAME }}@${{ secrets.HOST }}:/mnt/store/containers/homepage/

      # Use native SSH to restart the container
      - name: Restart Docker Container via SSH
        run: |
          ssh -i "${{ secrets.SSH_TNA_KEY }}" \
              -o StrictHostKeyChecking=no \
              ${{ secrets.SSH_TNA_USERNAME }}@${{ secrets.HOST }} \
              "docker container restart homepage"
