name: "[homepage] Update Config Files"

on:
  push:
    branches:
      - main
    paths:
      - "docker/homepage/config/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.SSH_TNA_USERNAME}}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_TNA_KEY }}
          source: "./docker/homepage/config/*"
          target: "/mnt/store/containers/homepage/"
          overwrite: true
          strip_components: 4

      - name: Restart Docker Container
        uses: fifsky/ssh-action@master
        with:
          user: ${{ secrets.SSH_TNA_USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_TNA_KEY }}
          command: |
            docker container restart homepage
