name: Monitor IP and Update Cloudflare

on:
  schedule:
    # Run the workflow every 30 minutes
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  monitor-ip:
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests cloudflare

      # Run the script
      - name: Run monitor script
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          DNS_RECORD_ID: ${{ secrets.CLOUDFLARE_DNS_RECORD_ID }}
        run: |
          python automation/ddns/cloudflare-update.py
