name: Test

on:
  push:
    branches: ["main"]
    paths:
      - "docker/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
